"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'el'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations = {
    en: {
        // Header
        'nav.find_dentist': 'Find a Dentist',
        'nav.services': 'Services',
        'nav.for_dentists': 'For Dentists',
        'nav.blog': 'Blog',
        'nav.sign_in': 'Sign In',
        'nav.logout': 'Logout',
        'nav.book_appointment': 'Book Appointment',
        'nav.dashboard': 'Dashboard',
        'nav.admin_dashboard': 'Admin Dashboard',
        'nav.go_dashboard': 'Go to Dashboard',
        'nav.go_admin_dashboard': 'Go to Admin Dashboard',

        // Hero
        'hero.title_part1': 'Find the perfect ',
        'hero.title_part2': 'dentist',
        'hero.title_part3': ' for your smile',
        'hero.subtitle': 'Book appointments instantly with top-rated dentists near you. Verified reviews, transparent pricing, and premium care.',
        'hero.verified_dentists': 'Verified Dentists',
        'hero.rating': '4.9/5 Average Rating',
        'hero.happy_patients': 'Trusted by Patients Across Greece',

        // Search Bar
        'search.find_dentist': 'Find a Dentist',
        'search.find_service': 'Find by Service',
        'search.placeholder_doctor': 'Doctor name, specialty, or condition',
        'search.placeholder_service': 'Treatment (e.g., Whitening, Implants)',
        'search.placeholder_location': 'City, neighborhood, or zip code',
        'search.placeholder_date': 'Any date',
        'search.button': 'Search',

        // How It Works
        'how_it_works.title': 'How Dentora Works',
        'how_it_works.subtitle': 'We make it simple to take care of your smile. Three easy steps to your next appointment.',
        'how_it_works.step1_title': 'Find your specialist',
        'how_it_works.step1_desc': 'Search by specialty, location, or insurance. Filter by verified reviews and availability.',
        'how_it_works.step2_title': 'Book instantly',
        'how_it_works.step2_desc': 'Choose a time that works for you. No phone calls, no waiting on hold. 24/7 booking.',
        'how_it_works.step3_title': 'Get better care',
        'how_it_works.step3_desc': 'Visit the dentist and leave a review. Your feedback helps others find great care.',

        // Featured Dentists
        'featured.title': 'Top-Rated Dentists',
        'featured.subtitle': 'Book with the most trusted specialists in your area.',
        'featured.next_available': 'Next Available',
        'featured.consultation': 'Consultation',
        'featured.book_appointment': 'Book Appointment',
        'featured.no_slots': 'No slots today',
        'featured.specialty.cosmetic': 'Cosmetic Dentist',
        'featured.specialty.orthodontist': 'Orthodontist',
        'featured.specialty.pediatric': 'Pediatric Dentist',
        'featured.specialty.surgeon': 'Oral Surgeon',
        'featured.specialty.general': 'General Dentist',
        'featured.specialty.periodontist': 'Periodontist',
        'featured.location.downtown': 'Downtown Dental, NY',
        'featured.location.smile': 'Smile Studio, Brooklyn',
        'featured.location.kids': 'Kids Care, Queens',
        'featured.location.surgical': 'Surgical Center, NY',
        'featured.slot.today': 'Today',
        'featured.slot.tomorrow': 'Tomorrow',
        'featured.slot.fri': 'Fri',

        // Popular Treatments
        'popular.title': 'Popular Treatments',
        'popular.subtitle': 'From routine checkups to complex procedures, find the right care for your needs.',
        'popular.view_all': 'View all treatments',
        'popular.bookings': 'bookings',
        'popular.whitening_title': 'Teeth Whitening',
        'popular.whitening_desc': 'Brighten your smile with professional whitening treatments.',
        'popular.root_canal_title': 'Root Canal',
        'popular.root_canal_desc': 'Save your natural tooth with painless root canal therapy.',
        'popular.implants_title': 'Dental Implants',
        'popular.implants_desc': 'Permanent solution for missing teeth with natural look.',
        'popular.veneers_title': 'Veneers',
        'popular.veneers_desc': 'Transform your smile with custom porcelain veneers.',
        'popular.emergency_title': 'Emergency Care',
        'popular.emergency_desc': 'Immediate relief for toothaches and dental injuries.',
        'popular.cleaning_title': 'Checkups & Cleaning',
        'popular.cleaning_desc': 'Routine care to keep your teeth and gums healthy.',

        // Services Detailed
        'services.whitening.title': 'Professional Teeth Whitening',
        'services.whitening.text': 'Professional teeth whitening is a safe and effective way to brighten your smile. We use advanced whitening gels and specialized lights to remove stains caused by coffee, tea, and age, giving you a radiant look in just one visit.',
        'services.whitening.details': 'Our whitening treatment can ligthen your teeth by several shades, providing instant results that last. We also offer take-home kits for maintenance.',

        'services.root_canal.title': 'Root Canal Treatment',
        'services.root_canal.text': 'A root canal treatment saves a severely infected or decayed tooth by removing the damaged pulp, cleaning the inner chamber, and sealing it. This procedure eliminates pain and prevents the need for tooth extraction.',
        'services.root_canal.details': 'Modern techniques make root canals as comfortable as getting a filling. We use digital imaging and local anesthesia to ensure a painless experience.',

        'services.implants.title': 'Advanced Dental Implants',
        'services.implants.text': 'Dental implants are the gold standard for replacing missing teeth. They consist of a titanium post that acts as a root, topped with a custom-made crown that looks and feels like a natural tooth.',
        'services.implants.details': 'Implants prevent bone loss and provide a permanent, stable solution. They function exactly like your natural teeth, allowing you to eat and speak with confidence.',

        'services.veneers.title': 'Porcelain Veneers',
        'services.veneers.text': 'Porcelain veneers are thin shells custom-made to fit over the front surface of your teeth. They are perfect for correcting chips, gaps, or deep stains, creating a Hollywood-style smile transformation.',
        'services.veneers.details': 'Veneers are highly resistant to stains and can last for over a decade with proper care. They offer the most natural-looking cosmetic enhancement available.',

        'services.emergency.title': '24/7 Emergency Care',
        'services.emergency.text': 'We provide immediate dental care for emergencies like severe toothaches, broken teeth, or lost fillings. Our team is dedicated to providing fast relief and saving your smile when the unexpected happens.',
        'services.emergency.details': 'If you are experiencing a dental emergency, call us immediately. We prioritize emergency cases to ensure you receive care as quickly as possible.',

        'services.cleaning.title': 'Checkups & Cleaning',
        'services.cleaning.text': 'Regular checkups and professional cleanings are essential for maintaining long-term oral health. Our thorough cleanings remove plaque and tartar that brushing alone can\'t reach.',
        'services.cleaning.details': 'Prevention is better than cure. Regular exams allow us to catch potential issues like cavities or gum disease before they become serious and expensive.',

        // Footer
        'footer.description': 'The world\'s leading platform for finding and booking the best dental care. Simple, transparent, and trusted by millions.',
        'footer.for_patients': 'For Patients',
        'footer.find_dentist': 'Find a Dentist',
        'footer.browse_treatments': 'Browse Treatments',
        'footer.blog': 'Dental Health Blog',
        'footer.faq': 'Patient FAQ',
        'footer.for_dentists': 'For Dentists',
        'footer.join_network': 'Join Our Network',
        'footer.practice_software': 'Practice Software',
        'footer.success_stories': 'Success Stories',
        'footer.dentist_login': 'Dentist Login',
        'footer.stay_updated': 'Stay Updated',
        'footer.newsletter_desc': 'Subscribe to our newsletter for the latest dental health tips and offers.',
        'footer.email_placeholder': 'Enter your email',
        'footer.subscribe': 'Subscribe',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.cookies': 'Cookie Settings',
        'footer.rights': 'All rights reserved.',

        // For Dentists Detailed
        'dentists.hero.title': 'The Modern Way to Grow Your Practice',
        'dentists.hero.subtitle': 'Join the leading dental network and connect with thousands of patients looking for premium care in your area.',
        'dentists.hero.cta': 'Join the Network',

        'dentists.feature1.title': 'Increase Your Visibility',
        'dentists.feature1.desc': 'Get listed in our premium search results. Our advanced SEO and marketing ensure your profile reaches the right patients at the right time.',
        'dentists.feature1.bullet1': 'SEO-optimized professional profile',
        'dentists.feature1.bullet2': 'Targeted patient marketing',
        'dentists.feature1.bullet3': 'Verified professional badge',
        'dentists.feature2.title': 'Smart Management',
        'dentists.feature2.desc': 'A complete practice management system. Manage bookings, patient history, and clinic availability with our intuitive professional dashboard.',
        'dentists.feature2.bullet1': '24/7 online booking system',
        'dentists.feature2.bullet2': 'Automated SMS/Email reminders',
        'dentists.feature2.bullet3': 'Digital patient records management',
        'dentists.feature3.title': 'Data-Driven Growth',
        'dentists.feature3.desc': 'Access detailed analytics on your practice performance. Understand patient trends and optimize your services for maximum efficiency.',
        'dentists.feature3.bullet1': 'Real-time revenue tracking',
        'dentists.feature3.bullet2': 'Patient retention analytics',
        'dentists.feature3.bullet3': 'Performance benchmarking',

        'dentists.stats.patients': 'New Patients Monthly',
        'dentists.stats.growth': 'Average Revenue Growth',
        'dentists.stats.satisfaction': 'Dentist Satisfaction',

        'dentists.cta.title': 'Ready to Modernize Your Clinic?',
        'dentists.cta.desc': 'Join thousands of top-rated dentists who have already transformed their practice with our platform.',
        'dentists.cta.button': 'Get Started Today',

        // Analytics
        'analytics.title': 'Performance Analytics',
        'analytics.page_views': 'Page Views',
        'analytics.bounce_rate': 'Bounce Rate',
        'analytics.sessions': 'Sessions',
        'analytics.session_length': 'Avg. Session Length',
        'analytics.pvs_per_session': 'PVs Per Session',
        'analytics.bounce_rate_last_7': 'Last 7 Days Bounce Rate',
        'analytics.render_vs_bounce': 'Render Speed vs Bounce',

        // Pages
        'pages.services.title': 'Our Services',
        'pages.services.desc': 'We offer a wide range of dental services including checkups, cleaning, whitening, and more.',
        'pages.for_dentists.title': 'For Dentists',
        'pages.for_dentists.desc': 'Join our network of top-rated dental professionals.',
        'pages.blog.title': 'Dental News & Advice',
        'pages.blog.desc': 'Expert insights from leading dental professionals. Stay updated with the latest in dental care, technology, and clinic news.',
        'blog.read_more': 'Read Article',
        'blog.posted_by': 'By Dr.',
        'blog.category.advice': 'Tips & Advice',
        'blog.category.case_study': 'Clinical Case Study',
        'blog.category.technology': 'Technology',
        'blog.category.news': 'Clinic News',
        'blog.no_posts': 'No articles found yet.',
        'blog.share': 'Share this article',
        'blog.related': 'Related Articles',
        'pages.faq.title': 'Frequently Asked Questions',
        'pages.faq.desc': 'Find answers to common questions.',
        'pages.privacy.title': 'Privacy Policy',
        'pages.privacy.desc': 'We take your privacy seriously.',
        'pages.terms.title': 'Terms of Service',
        'pages.terms.desc': 'By using our platform, you agree to these terms.',
        'pages.cookies.title': 'Cookie Policy',
        'pages.cookies.desc': 'We use cookies to improve your experience.',
        'pages.success_stories.title': 'Success Stories',
        'pages.success_stories.desc': 'See how other dental practices have grown.',
        'pages.practice_software.title': 'Practice Software',
        'pages.practice_software.desc': 'Manage your clinic efficiently.',
        'pages.dentist_login.title': 'Partner Login',
        'pages.dentist_login.desc': 'Access your practice dashboard',
        'pages.dentist_login.email_label': 'Work Email',
        'pages.dentist_login.password_label': 'Password',
        'pages.dentist_login.forgot_password': 'Forgot password?',
        'pages.dentist_login.remember_me': 'Remember me',
        'pages.dentist_login.login_button': 'Log In to Dashboard',
        'pages.dentist_login.new_here': 'New to Dentora?',
        'pages.dentist_login.join_network': 'Join our network',
        'pages.dentist_login.grow_title': 'Grow Your Practice',
        'pages.dentist_login.grow_desc': 'Join thousands of top-rated dentists.',
        'pages.login.title': 'Welcome back',
        'pages.login.desc': 'Enter your email to sign in',
        'pages.login.email_label': 'Email',
        'pages.login.password_label': 'Password',
        'pages.login.forgot_password': 'Forgot password?',
        'pages.login.remember_me': 'Remember me',
        'pages.login.login_button': 'Sign In',
        'pages.login.no_account': 'Don\'t have an account?',
        'pages.login.sign_up': 'Sign up',
        'pages.login.continue_google': 'Continue with Google',
        'pages.login.continue_facebook': 'Continue with Facebook',
        'pages.login.or_continue': 'Or continue with',
        'pages.login.already_account': 'Already have an account?',
        'pages.login.quote': '"Dentora has completely transformed how I manage my dental health."',
        'pages.login.patient_since': 'Patient since',
        'pages.search.title': 'Find a Dentist',
        'pages.search.desc': 'Search for the best dentists in your area.',
        'pages.search.results_found': 'results found',
        'pages.search.available_today': 'available today',
        'pages.search.map_view': 'Map View',
        'pages.search.sort_by': 'Sort by',
        'pages.search.recommended': 'Recommended',
        'pages.search.load_more': 'Load more dentists',
        'pages.search.filters': 'Filters',
        'pages.search.reset_all': 'Reset all',
        'pages.search.specialty': 'Specialty',
        'pages.search.availability': 'Availability',
        'pages.search.price': 'Consultation Price',
        'pages.search.rating': 'Rating',
        'pages.search.close': 'Close',
        'pages.search.reviews': 'reviews',
        'pages.search.video_consult': 'Video Consult',
        'pages.search.next_available': 'Next available',
        'pages.search.from': 'Consultation from',
        'pages.search.book_now': 'Book Appointment',
        'pages.search.this_week': 'This Week',
        'pages.search.weekends': 'Weekends',
        'pages.search.no_results': 'No dentists found',
        'pages.search.no_results_desc': 'Try adjusting your filters or search terms to find what you\'re looking for.',
        'pages.search.clear_all_filters': 'Clear all filters',
        'pages.search.near_me': 'Near me',
        'pages.search.locating': 'Locating...',
        'pages.search.location_placeholder': 'City, neighborhood, etc.',
        'pages.profile.about': 'About',
        'pages.profile.services_pricing': 'Services & Pricing',
        'pages.profile.patient_reviews': 'Patient Reviews',
        'pages.profile.book_appointment': 'Book Appointment',
        'pages.profile.open_until': 'Open today until',
        'pages.profile.years_exp': 'Years Exp.',
        'pages.profile.patients': 'Patients',
        'pages.profile.consultation_fee': 'Consultation Fee',
        'pages.profile.consultation_warning': 'Only the consultation fee is required for booking',
        'pages.profile.balance_info': 'Difference to be paid in clinical center',
        'pages.profile.book': 'Book',
        'pages.profile.available_slots': 'Available slots for',
        'pages.profile.no_card': 'No credit card required',
        'pages.profile.book_for': 'Book for',
        'pages.profile.helpful': 'Helpful',
        'pages.profile.required': 'Required',
        'pages.profile.no_reviews': 'No reviews yet for this dentist.',
        'pages.profile.available_today': 'Available Today',
        'pages.profile.no_desc': 'No description provided yet.',
        'pages.profile.to_be_updated': 'To be updated',
        'pages.profile.new_profile_desc': 'New dentist profile',
        'General Dentist': 'General Dentist',
        'Orthodontist': 'Orthodontist',
        'Cosmetic Dentist': 'Cosmetic Dentist',
        'Pediatric Dentist': 'Pediatric Dentist',
        'Oral Surgeon': 'Oral Surgeon',
        'Periodontist': 'Periodontist',
        'To be updated': 'To be updated',
        'New dentist profile': 'New dentist profile',
        'pages.profile.no_availability': 'No availability for this day',
        'pages.profile.booking_unavailable': 'Booking Unavailable',
        'pages.profile.secure_payment': 'Secure payment via Stripe • Instant confirmation',
        'pages.profile.booking_in_progress': 'Booking...',
        'pages.profile.about_text': 'Dr. Sarah Wilson is a highly skilled Cosmetic Dentist.',
        'pages.profile.education_text': 'She received her DDS from NYU.',
        'pages.profile.consultations': 'Consultations',
        'pages.profile.preventive_care': 'Preventive Care',
        'pages.profile.cosmetic_dentistry': 'Cosmetic Dentistry',
        'pages.profile.initial_consultation': 'Initial Consultation',
        'pages.profile.video_consultation': 'Video Consultation',
        'pages.profile.dental_cleaning': 'Dental Cleaning',
        'pages.profile.fluoride_treatment': 'Fluoride Treatment',
        'pages.profile.dental_sealants': 'Dental Sealants',
        'pages.profile.teeth_whitening': 'Teeth Whitening',
        'pages.profile.porcelain_veneers': 'Porcelain Veneers',
        'pages.profile.invisalign_consultation': 'Invisalign Consultation',
        'pages.profile.free': 'Free',
        'pages.profile.review1_text': 'Dr. Wilson is amazing!',
        'pages.profile.review2_text': 'Best dental experience I\'ve ever had.',
        'pages.profile.review3_text': 'Great service.',
        'pages.profile.weeks_ago': 'weeks ago',
        'pages.profile.month_ago': 'month ago',
        'pages.profile.months_ago': 'months ago',
        'pages.booking.title': 'Book Appointment',
        'pages.booking.step1': 'Service',
        'pages.booking.step2': 'Time',
        'pages.booking.step3': 'Info',
        'pages.booking.step4': 'Confirm',
        'pages.booking.review_confirm': 'Review & Confirm',
        'pages.booking.service': 'Service',
        'pages.booking.date_time': 'Date & Time',
        'pages.booking.patient': 'Patient',
        'pages.booking.total': 'Total',
        'pages.booking.back': 'Back',
        'pages.booking.continue': 'Continue',
        'pages.booking.confirm_booking': 'Confirm Booking',
        'pages.booking.confirm_date_time': 'Confirm Date & Time',
        'pages.booking.date': 'Date',
        'pages.booking.time': 'Time',
        'pages.booking.change_step_hint': 'You can change this in the previous step.',
        'pages.booking.patient_details': 'Patient Details',
        'pages.booking.first_name': 'First Name',
        'pages.booking.last_name': 'Last Name',
        'pages.booking.email': 'Email',
        'pages.booking.phone': 'Phone Number',
        'pages.booking.success_title': 'Appointment Confirmed!',
        'pages.booking.success_desc': 'Your appointment has been successfully booked.',
        'pages.booking.view_appointments': 'View My Appointments',
        'pages.booking.mock_date': 'Wed, Oct 14 • 10:00 AM',
        'pages.booking.mock_service': 'Dental Checkup',
        'pages.booking.required': 'is required',
        'pages.booking.invalid_email': 'Invalid email address',
        'pages.booking.invalid_phone': 'Valid phone number is required',
        'pages.booking.placeholder_first_name': 'John',
        'pages.booking.placeholder_last_name': 'Doe',
        'pages.booking.placeholder_email': 'john@example.com',
        'pages.booking.placeholder_phone': '(555) 123-4567',
        'pages.booking.prepayment_patient': '50€ down payment — deducted from the final amount',
        'pages.booking.prepayment_dentist': 'The patient has prepaid 50€ — balance at the appointment',
        'pages.booking.prepayment_note': 'the down payment is deducted from the final amount of works at the clinic',
        'pages.return_home': 'Return to Home',
        'days.mon': 'Mon',
        'days.tue': 'Tue',
        'days.wed': 'Wed',
        'days.thu': 'Thu',
        'days.fri': 'Fri',
        'days.sat': 'Sat',
        'days.sun': 'Sun',
        'months.jan': 'Jan',
        'months.feb': 'Feb',
        'months.mar': 'Mar',
        'months.apr': 'Apr',
        'months.may': 'May',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Aug',
        'months.sep': 'Sep',
        'months.oct': 'Oct',
        'months.nov': 'Nov',
        'months.dec': 'Dec',
        'months.january': 'January',
        'months.february': 'February',
        'months.march': 'March',
        'months.april': 'April',
        'months.may_full': 'May',
        'months.june': 'June',
        'months.july': 'July',
        'months.august': 'August',
        'months.september': 'September',
        'months.october': 'October',
        'months.november': 'November',
        'months.december': 'December',
        'days.monday': 'Monday',
        'days.tuesday': 'Tuesday',
        'days.wednesday': 'Wednesday',
        'days.thursday': 'Thursday',
        'days.friday': 'Friday',
        'days.saturday': 'Saturday',
        'days.sunday': 'Sunday',
        'time.am': 'AM',
        'time.pm': 'PM',
        'time.min': 'min',

        // Dashboard
        'dashboard.overview': 'Overview',
        'dashboard.bookings': 'Bookings',
        'dashboard.profile': 'Profile',
        'dashboard.availability': 'Availability',
        'dashboard.services': 'Services',
        'dashboard.my_articles': 'My Articles',
        'dashboard.settings': 'Settings',
        'dashboard.logout': 'Logout',

        // Dashboard Client
        'dashboard.setup_required': 'Account Setup Required',
        'dashboard.setup_desc': 'Please complete your profile configuration to access all dashboard features.',
        'dashboard.go_settings': 'Go to Settings',
        'dashboard.stats.total_patients': 'Total Patients',
        'dashboard.stats.unique_patients': 'All time unique patients',
        'dashboard.stats.upcoming_bookings': 'Upcoming Bookings',
        'dashboard.stats.recent_future': 'Recent and future slots',
        'dashboard.stats.average_rating': 'Average Rating',
        'dashboard.stats.verified_reviews': 'verified reviews',
        'dashboard.stats.total_revenue': 'Total Revenue',
        'dashboard.stats.from_confirmed': 'From confirmed appointments',
        'dashboard.clinic_closed': 'Clinic Closed Today',
        'dashboard.clinic_open': 'Clinic Open Today',
        'dashboard.clinic_closed_desc': 'Today is marked as non-available. No patients can book for today.',
        'dashboard.clinic_open_desc': 'You are open today from',
        'dashboard.to': 'to',
        'dashboard.change': 'Change',
        'dashboard.profile_review': 'Profile Under Review',
        'dashboard.verification_required': 'Verification Required',
        'dashboard.docs_reviewed': 'Your documents are being reviewed.',
        'dashboard.upload_degree': 'Upload your professional degree.',
        'dashboard.submit': 'Submit',
        'dashboard.complete_payment': 'Complete Payment Setup',
        'dashboard.setup_payment': 'Setup Payments',
        'dashboard.in_progress': 'In Progress',
        'dashboard.stripe_incomplete': 'Your Stripe account is created but needs more information to start receiving payments. Complete the verification now.',
        'dashboard.stripe_required': 'To receive payments from bookings, you need to connect your Stripe account. This is required to show your profile to patients.',
        'dashboard.resume_stripe': 'Resume Stripe Setup',
        'dashboard.connect_stripe': 'Connect Stripe',
        'dashboard.dentist_dashboard': 'Dentist Dashboard',
        'dashboard.welcome_dentist': 'Welcome back! Manage your practice with real-time data.',
        'dashboard.upcoming_appointments': 'Upcoming Appointments',
        'dashboard.view_all': 'View All',
        'dashboard.no_upcoming': 'No upcoming appointments found.',
        'dashboard.quick_actions': 'Quick Actions',
        'dashboard.update_availability': 'Update Availability',
        'dashboard.manage_services': 'Manage Services',
        'dashboard.view_reviews': 'View All Reviews',
        'dashboard.my_dashboard': 'My Dashboard',
        'dashboard.patient_welcome': 'Keep track of your dental health and appointments.',
        'dashboard.upcoming': 'Upcoming',
        'dashboard.completed': 'Completed',
        'dashboard.are_you_dentist': 'Are you a Dentist?',
        'dashboard.dentist_promo': 'Create your professional profile, manage appointments, and grow your practice with Dentist Anytime.',
        'dashboard.switch_dentist': 'Switch to Dentist Account',
        'dashboard.find_new_dentist': 'Find New Dentist',
        'dashboard.prepaid': 'PREPAID',
        'dashboard.no_upcoming_patient': 'No upcoming appointments found.',
        'dashboard.book_first': 'Book Your First Appointment',

        // Profile Form
        'profile.title': 'Public Profile',
        'profile.subtitle': 'Manage how your profile appears to patients.',
        'profile.saving': 'Saving...',
        'profile.save_changes': 'Save Changes',
        'profile.photo_title': 'Profile Photo',
        'profile.change_photo': 'Change Photo',
        'profile.photo_hint': 'JPG, PNG or GIF. Max size 2MB.',
        'profile.basic_info': 'Basic Information',
        'profile.full_name': 'Full Name',
        'profile.specialty': 'Specialty',
        'profile.experience': 'Years of Experience',
        'profile.price': 'Consultation Fee (€)',
        'profile.clinic_address': 'Clinic Address',
        'profile.search_address': 'Search Address',
        'profile.search_address_hint': 'Start typing your clinic address to auto-fill the fields below',
        'profile.search_placeholder': 'Search for your clinic address...',
        'profile.city': 'City',
        'profile.city_placeholder': 'e.g. Thessaloniki',
        'profile.street': 'Street Address',
        'profile.street_placeholder': 'e.g. Tsimiski',
        'profile.house_number': 'House / Building Number',
        'profile.house_number_placeholder': 'e.g. 42',
        'profile.coordinates_saved': '✓ Location coordinates saved — your clinic will appear on the map',
        'profile.bio_title': 'Professional Bio',
        'profile.about_me': 'About Me',
        'profile.about_placeholder': 'Tell patients about your experience and approach to care...',
        'profile.education': 'Education & Certifications',
        'profile.education_placeholder': 'List your degrees and specialized training...',
        'profile.verification_status': 'Verification Status',
        'profile.verified': 'Verified',
        'profile.under_review': 'Under Review',
        'profile.not_verified': 'Not Verified',
        'profile.verification_hint': 'To activate your profile and allow patients to book appointments, you must upload your professional degree or certification for review.',
        'profile.upload_degree': 'Upload Degree (Image URL)',
        'profile.degree_placeholder': 'Paste image URL of your degree',
        'profile.submit': 'Submit',
        'profile.degree_reviewing': 'Your degree is currently being reviewed by our team. You will be notified once verified.',
        'profile.fully_verified': 'Your account is fully verified and visible to patients.',

        // Bookings
        'bookings.title': 'Appointments',
        'bookings.subtitle': 'Manage and track all your patient bookings.',
        'bookings.calendar_view': 'Calendar View',
        'bookings.export_list': 'Export List',
        'bookings.recent': 'Recent Bookings',
        'bookings.patient': 'Patient',
        'bookings.service': 'Service',
        'bookings.date_time': 'Date & Time',
        'bookings.status': 'Status',
        'bookings.actions': 'Actions',
        'bookings.no_bookings': 'No bookings found.',


        // Availability
        'availability.manage': 'Manage Availability',
        'availability.manage_desc': 'Organize your weekly schedule and handle specific date overrides.',
        'availability.calendar_view': 'Calendar View',
        'availability.weekly_schedule': 'Weekly Schedule',
        'availability.custom_day': 'Custom Day Organizer',
        'availability.custom_day_desc': 'Click on any day to precisely adjust your working hours for that specific date. You can add multiple time blocks (e.g., morning and afternoon) or mark yourself as closed.',
        'availability.standard_weekly': 'Standard Weekly Schedule',
        'availability.standard_weekly_desc': 'These blocks will repeat every week unless overridden in the calendar.',
        'availability.save_weekly': 'Save Weekly Schedule',
        'availability.enabled': 'Enabled',
        'availability.disabled': 'Disabled',
        'availability.add_block': 'Add Another Block',
        'availability.no_hours': 'No hours defined. Clinic is closed on this day.',
        'availability.edit_all_hours': 'Edit All Hours',
        'availability.available': 'Available',
        'availability.closed': 'Closed',
        'availability.click_any_day': 'Click any day to manage multiple time blocks and gaps.',
        'availability.edit_day': 'Edit Day Organizer',
        'availability.clinic_status': 'Clinic Status',
        'availability.clinic_status_desc': 'Is the clinic accepting appointments for this day?',
        'availability.available_blocks': 'Available Time Blocks',
        'availability.starts_at': 'Starts At',
        'availability.ends_at': 'Ends At',
        'availability.add_time_block': 'Add Another Time Block',
        'availability.clinic_is_closed': 'Clinic is CLOSED',
        'availability.no_slots': 'No slots will be generated. This day will be completely blocked for all patients.',
        'availability.reset_day': 'Reset Day',
        'availability.save_variations': 'Save Variations',
        'availability.more': 'more',
        'availability.override': 'Override',

        // Services
        'services.title': 'Services & Pricing',
        'services.subtitle': 'List the dental services you offer and their prices.',
        'services.add': 'Add Service',
        'services.name': 'Service Name',
        'services.name_placeholder': 'e.g. Teeth Whitening',
        'services.price': 'Price (€)',
        'services.duration': 'Duration (min)',
        'services.no_services': 'No services added yet. Click "Add Service" to start.',
        'services.updated': 'Services updated!',
        'services.failed': 'Failed to update services.',

        // Settings
        'settings.title': 'Settings',
        'settings.subtitle': 'Manage your account settings and preferences.',
        'settings.email_notif': 'Email Notifications',
        'settings.new_bookings': 'New Bookings',
        'settings.new_bookings_desc': 'Receive an email when a new patient books an appointment.',
        'settings.reminders': 'Reminders',
        'settings.reminders_desc': 'Receive reminders about upcoming appointments.',
        'settings.danger_zone': 'Danger Zone',
        'settings.delete_account': 'Delete Account',
        'settings.delete_account_desc': 'Permanently delete your account and all data. This action cannot be undone.',
        'settings.deleting': 'Deleting...',
        'settings.delete_confirm': 'Are you sure you want to delete your account? This action cannot be undone.',
        'settings.delete_error': 'An error occurred while deleting your account. Please try again.',

        // Blog
        'blog.my_articles_title': 'My Articles',
        'blog.my_articles_desc': 'Manage your clinical insights and patient advice.',
        'blog.write_new': 'Write New Article',
        'blog.view': 'View',
        'blog.edit': 'Edit',
        'blog.no_articles': 'No articles yet',
        'blog.share_expertise': 'Share your expertise with patients and build trust by writing your first article.',
        'blog.start_writing': 'Start Writing',
        'blog.delete_confirm': 'Are you sure you want to delete this article?',
        'blog.delete_failed': 'Delete failed',

        // Blog Editor
        'blog.back': 'Back to My Articles',
        'blog.write_title': 'Write New Article',
        'blog.publish': 'Publish Article',
        'blog.publishing': 'Publishing...',
        'blog.titles': 'Titles',
        'blog.en_title': 'English Title',
        'blog.en_title_ph': 'e.g. The importance of daily flossing',
        'blog.el_title': 'Ελληνικός Τίτλος',
        'blog.el_title_ph': 'π.χ. Η σημασία του καθημερινού νήματος',
        'blog.content_title': 'Article Content',
        'blog.en_content': 'English Content',
        'blog.en_content_ph': 'Write your article in English...',
        'blog.el_content': 'Ελληνικό Περιεχόμενο',
        'blog.el_content_ph': 'Γράψτε το άρθρο σας στα Ελληνικά...',
        'blog.settings': 'Settings',
        'blog.category': 'Category',
        'blog.cat_tips': 'Tips & Advice',
        'blog.cat_case': 'Clinical Case Study',
        'blog.cat_tech': 'Technology',
        'blog.cat_news': 'Clinic News',
        'blog.slug': 'Custom Slug (Optional)',
        'blog.slug_ph': 'the-importance-of-flossing',
        'blog.slug_hint': 'Leaves empty to auto-generate from title.',
        'blog.cover_image': 'Cover Image',
        'blog.image_url': 'Image URL',
        'blog.image_ph': 'Paste image URL...',
        'blog.create_failed': 'Failed to create article',
    },
    el: {
        // Header
        'nav.find_dentist': 'Βρείτε Οδοντίατρο',
        'nav.services': 'Υπηρεσίες',
        'nav.for_dentists': 'Για Οδοντιάτρους',
        'nav.blog': 'Blog',
        'nav.sign_in': 'Σύνδεση',
        'nav.logout': 'Αποσύνδεση',
        'nav.book_appointment': 'Κλείστε Ραντεβού',
        'nav.dashboard': 'Πίνακας Ελέγχου',
        'nav.admin_dashboard': 'Πίνακας Διαχείρισης',
        'nav.go_dashboard': 'Μετάβαση στον Πίνακα Ελέγχου',
        'nav.go_admin_dashboard': 'Μετάβαση στον Πίνακα Διαχείρισης',

        // Hero
        'hero.title_part1': 'Βρείτε τον τέλειο ',
        'hero.title_part2': 'οδοντίατρο',
        'hero.title_part3': ' για το χαμόγελό σας',
        'hero.subtitle': 'Κλείστε ραντεβού άμεσα με τους καλύτερους οδοντιάτρους κοντά σας.',
        'hero.verified_dentists': 'Πιστοποιημένοι Οδοντίατροι',
        'hero.rating': '4.9/5 Μέση Βαθμολογία',
        'hero.happy_patients': 'Εμπιστοσύνη Ασθενών σε Όλη την Ελλάδα',

        // Search Bar
        'search.find_dentist': 'Βρείτε Οδοντίατρο',
        'search.find_service': 'Αναζήτηση ανά Υπηρεσία',
        'search.placeholder_doctor': 'Όνομα ιατρού, ειδικότητα ή πάθηση',
        'search.placeholder_service': 'Θεραπεία',
        'search.placeholder_location': 'Πόλη, περιοχή ή ΤΚ',
        'search.placeholder_date': 'Οποιαδήποτε ημερομηνία',
        'search.button': 'Αναζήτηση',

        // How It Works
        'how_it_works.title': 'Πώς λειτουργεί το Dentora',
        'how_it_works.subtitle': 'Κάνουμε απλή τη φροντίδα του χαμόγελού σας.',
        'how_it_works.step1_title': 'Βρείτε τον ειδικό σας',
        'how_it_works.step1_desc': 'Αναζητήστε ανά ειδικότητα, τοποθεσία ή ασφάλεια.',
        'how_it_works.step2_title': 'Κλείστε άμεσα',
        'how_it_works.step2_desc': 'Επιλέξτε μια ώρα που σας εξυπηρετεί.',
        'how_it_works.step3_title': 'Λάβετε καλύτερη φροντίδα',
        'how_it_works.step3_desc': 'Επισκεφθείτε τον οδοντίατρο και αφήστε μια κριτική.',

        // Featured Dentists
        'featured.title': 'Κορυφαίοι Οδοντίατροι',
        'featured.subtitle': 'Κλείστε ραντεβού με τους πιο έμπιστους ειδικούς.',
        'featured.next_available': 'Επόμενο Διαθέσιμο',
        'featured.consultation': 'Συνεδρία',
        'featured.book_appointment': 'Κλείστε Ραντεβού',
        'featured.no_slots': 'Χωρίς διαθεσιμότητα σήμερα',
        'featured.specialty.cosmetic': 'Αισθητικός Οδοντίατρος',
        'featured.specialty.orthodontist': 'Ορθοδοντικός',
        'featured.specialty.pediatric': 'Παιδοδοντίατρος',
        'featured.specialty.surgeon': 'Γναθοχειρουργός',
        'featured.specialty.general': 'Γενικός Οδοντίατρος',
        'featured.specialty.periodontist': 'Περιοδοντολόγος',
        'featured.location.downtown': 'Κέντρο Οδοντιατρικής, Αθήνα',
        'featured.location.smile': 'Smile Studio, Κηφισιά',
        'featured.location.kids': 'Kids Care, Γλυφάδα',
        'featured.location.surgical': 'Χειρουργικό Κέντρο, Πειραιάς',
        'featured.slot.today': 'Σήμερα',
        'featured.slot.tomorrow': 'Αύριο',
        'featured.slot.fri': 'Παρ',

        // Popular Treatments
        'popular.title': 'Δημοφιλείς Θεραπείες',
        'popular.subtitle': 'Βρείτε την κατάλληλη φροντίδα για τις ανάγκες σας.',
        'popular.view_all': 'Δείτε όλες τις θεραπείες',
        'popular.bookings': 'κρατήσεις',
        'popular.whitening_title': 'Λεύκανση Δοντιών',
        'popular.whitening_desc': 'Φωτίστε το χαμόγελό σας.',
        'popular.root_canal_title': 'Απονεύρωση',
        'popular.root_canal_desc': 'Σώστε το φυσικό σας δόντι.',
        'popular.implants_title': 'Οδοντικά Εμφυτεύματα',
        'popular.implants_desc': 'Μόνιμη λύση για ελλείποντα δόντια.',
        'popular.veneers_title': 'Όψεις',
        'popular.veneers_desc': 'Μεταμορφώστε το χαμόγελό σας.',
        'popular.emergency_title': 'Επείγουσα Φροντίδα',
        'popular.emergency_desc': 'Άμεση ανακούφιση.',
        'popular.cleaning_title': 'Έλεγχος & Καθαρισμός',
        'popular.cleaning_desc': 'Τακτική φροντίδα.',

        // Services Detailed
        'services.whitening.title': 'Επαγγελματική Λεύκανση Δοντιών',
        'services.whitening.text': 'Η επαγγελματική λεύκανση δοντιών είναι ένας ασφαλής και αποτελεσματικός τρόπος για να φωτίσετε το χαμόγελό σας. Χρησιμοποιούμε προηγμένα τζελ λεύκανσης και εξειδικευμένο φως για να αφαιρέσουμε λεκέδες που προκαλούνται από καφέ, τσάι και την πάροδο του χρόνου, χαρίζοντάς σας ένα ακτινοβόλο χαμόγελο σε μία μόνο επίσκεψη.',
        'services.whitening.details': 'Η θεραπεία λεύκανσης μπορεί να φωτίσει τα δόντια σας κατά αρκετούς τόνους, παρέχοντας άμεσα αποτελέσματα που διαρκούν. Προσφέρουμε επίσης κιτ για το σπίτι για συντήρηση του αποτελέσματος.',

        'services.root_canal.title': 'Ενδοδοντική Θεραπεία (Απονεύρωση)',
        'services.root_canal.text': 'Η ενδοδοντική θεραπεία σώζει ένα σοβαρά μολυσμένο ή φθαρμένο δόντι αφαιρώντας τον κατεστραμμένο πολφό, καθαρίζοντας τον εσωτερικό θάλαμο και σφραγίζοντάς τον. Αυτή η διαδικασία εξαλείφει τον πόνο και αποτρέπει την ανάγκη εξαγωγής του δοντιού.',
        'services.root_canal.details': 'Οι σύγχρονες τεχνικές καθιστούν την απονεύρωση τόσο άνετη όσο ένα απλό σφράγισμα. Χρησιμοποιούμε ψηφιακή απεικόνιση και τοπική αναισθησία για μια ανώδυνη εμπειρία.',

        'services.implants.title': 'Προηγμένα Οδοντικά Εμφυτεύματα',
        'services.implants.text': 'Τα οδοντικά εμφυτεύματα είναι η κορυφαία λύση για την αντικατάσταση ελλειπόντων δοντιών. Αποτελούνται από έναν άξονα τιτανίου που λειτουργεί ως ρίζα, και μια εξατομικευμένη στεφάνη που μοιάζει και έχει την αίσθηση φυσικού δοντιού.',
        'services.implants.details': 'Τα εμφυτεύματα προλαμβάνουν την οστική απώλεια και παρέχουν μια μόνιμη, σταθερή λύση. Λειτουργούν ακριβώς όπως τα φυσικά σας δόντια.',

        'services.veneers.title': 'Όψεις Πορσελάνης',
        'services.veneers.text': 'Οι όψεις πορσελάνης είναι λεπτά κελύφη κατασκευασμένα κατά παραγγελία για να εφαρμόζουν στην μπροστινή επιφάνεια των δοντιών σας. Είναι ιδανικές για τη διόρθωση σπασιμάτων, κενών ή έντονων δυσχρωμιών.',
        'services.veneers.details': 'Οι όψεις είναι εξαιρετικά ανθεκτικές στους λεκέδες και μπορούν να διαρκέσουν πάνω από μια δεκαετία με τη σωστή φροντίδα.',

        'services.emergency.title': '24/7 Επείγουσα Φροντίδα',
        'services.emergency.text': 'Παρέχουμε άμεση οδοντιατρική φροντίδα για επείγοντα περιστατικά όπως έντονους πονόδοντους, σπασμένα δόντια ή απώλεια σφραγισμάτων. Η ομάδα μας είναι αφοσιωμένη στην παροχή άμεσης ανακούφισης.',
        'services.emergency.details': 'Εάν αντιμετωπίζετε κάποιο επείγον οδοντιατρικό πρόβλημα, καλέστε μας αμέσως. Δίνουμε προτεραιότητα στα επείγοντα περιστατικά.',

        'services.cleaning.title': 'Έλεγχος & Καθαρισμός',
        'services.cleaning.text': 'Οι τακτικοί έλεγχοι και ο επαγγελματικός καθαρισμός είναι απαραίτητα για τη διατήρηση της μακροχρόνιας στοματικής υγείας. Ο καθαρισμός αφαιρεί την πλάκα και την πέτρα που το βούρτσισμα δεν μπορεί να φτάσει.',
        'services.cleaning.details': 'Η πρόληψη είναι η καλύτερη θεραπεία. Οι τακτικές εξετάσεις μας επιτρέπουν να εντοπίζουμε πιθανά προβλήματα πριν γίνουν σοβαρά και δαπανηρά.',

        // Footer
        'footer.description': 'Η κορυφαία πλατφόρμα για την εύρεση και κράτηση οδοντιατρικής φροντίδας.',
        'footer.for_patients': 'Για Ασθενείς',
        'footer.find_dentist': 'Βρείτε Οδοντίατρο',
        'footer.browse_treatments': 'Περιήγηση Θεραπειών',
        'footer.blog': 'Blog Στοματικής Υγείας',
        'footer.faq': 'Συχνές Ερωτήσεις Ασθενών',
        'footer.for_dentists': 'Για Οδοντιάτρους',
        'footer.join_network': 'Γίνετε Μέλος του Δικτύου μας',
        'footer.practice_software': 'Λογισμικό Ιατρείου',
        'footer.success_stories': 'Ιστορίες Επιτυχίας',
        'footer.dentist_login': 'Σύνδεση Οδοντιάτρου',
        'footer.stay_updated': 'Μείνετε Ενημερωμένοι',
        'footer.newsletter_desc': 'Εγγραφείτε στο ενημερωτικό μας δελτίο.',
        'footer.email_placeholder': 'Εισάγετε το email σας',
        'footer.subscribe': 'Εγγραφή',
        'footer.privacy': 'Πολιτική Απορρήτου',
        'footer.terms': 'Όροι Χρήσης',
        'footer.cookies': 'Ρυθμίσεις Cookies',
        'footer.rights': 'Με την επιφύλαξη παντός δικαιώματος.',

        // For Dentists Detailed
        'dentists.hero.title': 'Ο Σύγχρονος Τρόπος για να Αναπτύξετε το Ιατρείο σας',
        'dentists.hero.subtitle': 'Γίνετε μέλος του κορυφαίου οδοντιατρικού δικτύου και συνδεθείτε με χιλιάδες ασθενείς που αναζητούν ποιοτική φροντίδα.',
        'dentists.hero.cta': 'Γίνετε Μέλος του Δικτύου',

        'dentists.feature1.title': 'Αυξήστε την Προβολή σας',
        'dentists.feature1.desc': 'Εμφανιστείτε στα κορυφαία αποτελέσματα αναζήτησης. Το προηγμένο SEO και το marketing μας διασφαλίζουν ότι το προφίλ σας φτάνει στους σωστούς ασθενείς.',
        'dentists.feature1.bullet1': 'SEO-βελτιστοποιημένο προφίλ',
        'dentists.feature1.bullet2': 'Στοχευμένο marketing ασθενών',
        'dentists.feature1.bullet3': 'Σήμα πιστοποιημένου επαγγελματία',
        'dentists.feature2.title': 'Έξυπνη Διαχείριση',
        'dentists.feature2.desc': 'Ένα πλήρες σύστημα διαχείρισης ιατρείου. Διαχειριστείτε κρατήσεις, ιστορικό ασθενών και διαθεσιμότητα με τον διαισθητικό πίνακα ελέγχου.',
        'dentists.feature2.bullet1': 'Σύστημα κρατήσεων 24/7',
        'dentists.feature2.bullet2': 'Αυτοματοποιημένες υπενθυμίσεις SMS/Email',
        'dentists.feature2.bullet3': 'Ψηφιακή διαχείριση αρχείων ασθενών',
        'dentists.feature3.title': 'Ανάπτυξη βασισμένη σε Δεδομένα',
        'dentists.feature3.desc': 'Αποκτήστε πρόσβαση σε λεπτομερή στατιστικά στοιχεία για την απόδοση του ιατρείου σας. Κατανοήστε τις τάσεις των ασθενών.',
        'dentists.feature3.bullet1': 'Παρακολούθηση εσόδων σε πραγματικό χρόνο',
        'dentists.feature3.bullet2': 'Ανάλυση διατήρησης ασθενών',
        'dentists.feature3.bullet3': 'Συγκριτική αξιολόγηση απόδοσης',

        'dentists.stats.patients': 'Νέοι Ασθενείς Μηνιαία',
        'dentists.stats.growth': 'Μέση Αύξηση Εσόδων',
        'dentists.stats.satisfaction': 'Ικανοποίηση Οδοντιάτρων',

        'dentists.cta.title': 'Έτοιμοι να Εκσυγχρονίσετε την Κλινική σας;',
        'dentists.cta.desc': 'Γίνετε μέλος χιλιάδων κορυφαίων οδοντιάτρων που έχουν ήδη μεταμορφώσει το ιατρείο τους με την πλατφόρμα μας.',
        'dentists.cta.button': 'Ξεκινήστε Σήμερα',

        // Analytics
        'analytics.title': 'Ανάλυση Απόδοσης',
        'analytics.page_views': 'Προβολές Σελίδας',
        'analytics.bounce_rate': 'Ποσοστό Εγκατάλειψης',
        'analytics.sessions': 'Συνεδρίες',
        'analytics.session_length': 'Μέση Διάρκεια Συνεδρίας',
        'analytics.pvs_per_session': 'Προβολές ανά Συνεδρία',
        'analytics.bounce_rate_last_7': 'Εγκατάλειψη τελευταίων 7 ημερών',
        'analytics.render_vs_bounce': 'Ταχύτητα vs Εγκατάλειψη',

        // Pages
        'pages.services.title': 'Οι Υπηρεσίες μας',
        'pages.services.desc': 'Προσφέρουμε ένα ευρύ φάσμα οδοντιατρικών υπηρεσιών.',
        'pages.for_dentists.title': 'Για Οδοντιάτρους',
        'pages.for_dentists.desc': 'Γίνετε μέλος του δικτύου μας.',
        'pages.blog.title': 'Blog Στοματικής Υγείας',
        'pages.blog.desc': 'Διαβάστε τα τελευταία άρθρα.',
        'pages.faq.title': 'Συχνές Ερωτήσεις',
        'pages.faq.desc': 'Βρείτε απαντήσεις σε κοινές ερωτήσεις.',
        'pages.privacy.title': 'Πολιτική Απορρήτου',
        'pages.privacy.desc': 'Λαμβάνουμε σοβαρά υπόψη το απόρρητό σας.',
        'pages.terms.title': 'Όροι Χρήσης',
        'pages.terms.desc': 'Χρησιμοποιώντας την πλατφόρμα μας, συμφωνείτε με αυτούς τους όρους.',
        'pages.cookies.title': 'Πολιτική Cookies',
        'pages.cookies.desc': 'Χρησιμοποιούμε cookies για να βελτιώσουμε την εμπειρία σας.',
        'pages.success_stories.title': 'Ιστορίες Επιτυχίας',
        'pages.success_stories.desc': 'Δείτε πώς άλλα οδοντιατρεία αναπτύχθηκαν.',
        'pages.practice_software.title': 'Λογισμικό Ιατρείου',
        'pages.practice_software.desc': 'Διαχειριστείτε την κλινική σας αποτελεσματικά.',
        'pages.dentist_login.title': 'Σύνδεση Συνεργάτη',
        'pages.dentist_login.desc': 'Αποκτήστε πρόσβαση στον πίνακα ελέγχου',
        'pages.dentist_login.email_label': 'Email Εργασίας',
        'pages.dentist_login.password_label': 'Κωδικός Πρόσβασης',
        'pages.dentist_login.forgot_password': 'Ξεχάσατε τον κωδικό σας;',
        'pages.dentist_login.remember_me': 'Να με θυμάσαι',
        'pages.dentist_login.login_button': 'Σύνδεση στον Πίνακα Ελέγχου',
        'pages.dentist_login.new_here': 'Νέος στο Dentora?',
        'pages.dentist_login.join_network': 'Γίνετε μέλος του δικτύου μας',
        'pages.dentist_login.grow_title': 'Αναπτύξτε το Ιατρείο σας',
        'pages.dentist_login.grow_desc': 'Γίνετε μέλος χιλιάδων κορυφαίων οδοντιάτρων.',
        'pages.login.title': 'Καλώς ήρθατε ξανά',
        'pages.login.desc': 'Εισάγετε το email σας για να συνδεθείτε',
        'pages.login.email_label': 'Email',
        'pages.login.password_label': 'Κωδικός Πρόσβασης',
        'pages.login.forgot_password': 'Ξεχάσατε τον κωδικό σας;',
        'pages.login.remember_me': 'Να με θυμάσαι',
        'pages.login.login_button': 'Σύνδεση',
        'pages.login.no_account': 'Δεν έχετε λογαριασμό;',
        'pages.login.sign_up': 'Εγγραφή',
        'pages.login.continue_google': 'Συνέχεια μέσω Google',
        'pages.login.continue_facebook': 'Συνέχεια μέσω Facebook',
        'pages.login.or_continue': 'Ή συνεχίστε με',
        'pages.login.already_account': 'Έχετε ήδη λογαριασμό;',
        'pages.login.quote': '"Το Dentora έχει μεταμορφώσει τον τρόπο που διαχειρίζομαι την υγεία μου."',
        'pages.login.patient_since': 'Ασθενής από το',
        'pages.search.title': 'Βρείτε Οδοντίατρο',
        'pages.search.desc': 'Αναζητήστε τους καλύτερους οδοντιάτρους.',
        'pages.search.results_found': 'αποτελέσματα βρέθηκαν',
        'pages.search.available_today': 'διαθέσιμοι σήμερα',
        'pages.search.map_view': 'Προβολή Χάρτη',
        'pages.search.sort_by': 'Ταξινόμηση κατά',
        'pages.search.recommended': 'Προτεινόμενα',
        'pages.search.load_more': 'Περισσότεροι οδοντίατροι',
        'pages.search.filters': 'Φίλτρα',
        'pages.search.reset_all': 'Επαναφορά',
        'pages.search.specialty': 'Ειδικότητα',
        'pages.search.availability': 'Διαθεσιμότητα',
        'pages.search.price': 'Τιμή Επίσκεψης',
        'pages.search.rating': 'Αξιολόγηση',
        'pages.search.close': 'Κλείσιμο',
        'pages.search.reviews': 'κριτικές',
        'pages.search.video_consult': 'Βίντεο-Συνεδρία',
        'pages.search.next_available': 'Επόμενο διαθέσιμο',
        'pages.search.from': 'Επίσκεψη από',
        'pages.search.book_now': 'Κλείστε Ραντεβού',
        'pages.search.this_week': 'Αυτή την εβδομάδα',
        'pages.search.weekends': 'Σαββατοκύριακα',
        'pages.search.no_results': 'Δεν βρέθηκαν οδοντίατροι',
        'pages.search.no_results_desc': 'Δοκιμάστε να αλλάξετε τα φίλτρα ή τους όρους αναζήτησης.',
        'pages.search.clear_all_filters': 'Καθαρισμός όλων των φίλτρων',
        'pages.search.near_me': 'Κοντά μου',
        'pages.search.locating': 'Εντοπισμός...',
        'pages.search.location_placeholder': 'Πόλη, περιοχή κλπ.',
        'pages.profile.about': 'Σχετικά',
        'pages.profile.services_pricing': 'Υπηρεσίες & Τιμές',
        'pages.profile.patient_reviews': 'Κριτικές Ασθενών',
        'pages.profile.book_appointment': 'Κλείστε Ραντεβού',
        'pages.profile.open_until': 'Ανοιχτά σήμερα έως',
        'pages.profile.years_exp': 'Χρόνια Εμπειρίας',
        'pages.profile.patients': 'Ασθενείς',
        'pages.profile.consultation_fee': 'Κόστος Επίσκεψης',
        'pages.profile.consultation_warning': 'Απαιτείται μόνο το κόστος επίσκεψης για την κράτηση',
        'pages.profile.balance_info': 'Η διαφορά θα πληρωθεί στο ιατρείο',
        'pages.profile.book': 'Κράτηση',
        'pages.profile.available_slots': 'Διαθέσιμα ραντεβού για',
        'pages.profile.no_card': 'Δεν απαιτείται κάρτα',
        'pages.profile.select_time': 'Επιλέξτε ώρα',
        'pages.profile.book_for': 'Κράτηση για',
        'pages.profile.helpful': 'Χρήσιμο',
        'pages.profile.required': 'ΑΠΑΡΑΙΤΗΤΟ',
        'pages.profile.no_reviews': 'Δεν υπάρχουν ακόμη κριτικές για αυτόν τον οδοντίατρο.',
        'pages.profile.available_today': 'Διαθέσιμος Σήμερα',
        'pages.profile.no_desc': 'Δεν έχει δοθεί περιγραφή ακόμη.',
        'pages.profile.to_be_updated': 'Θα ενημερωθεί σύντομα',
        'pages.profile.new_profile_desc': 'Νέο προφίλ οδοντιάτρου',
        'General Dentist': 'Γενικός Οδοντίατρος',
        'Orthodontist': 'Ορθοδοντικός',
        'Cosmetic Dentist': 'Αισθητικός Οδοντίατρος',
        'Pediatric Dentist': 'Παιδοδοντίατρος',
        'Oral Surgeon': 'Γναθοχειρουργός',
        'Periodontist': 'Περιοδοντολόγος',
        'To be updated': 'Θα ενημερωθεί σύντομα',
        'New dentist profile': 'Νέο προφίλ οδοντιάτρου',
        'pages.profile.no_availability': 'Καμία διαθεσιμότητα για αυτήν την ημέρα',
        'pages.profile.booking_unavailable': 'Μη διαθέσιμη κράτηση',
        'pages.profile.secure_payment': 'Ασφαλής πληρωμή μέσω Stripe • Άμεση επιβεβαίωση',
        'pages.profile.booking_in_progress': 'Κράτηση...',
        'pages.profile.about_text': 'Η Δρ. Sarah Wilson είναι μια εξαιρετική οδοντίατρος.',
        'pages.profile.education_text': 'Έλαβε το πτυχίο της από το NYU.',
        'pages.profile.consultations': 'Συνεδρίες',
        'pages.profile.preventive_care': 'Προληπτική Φροντίδα',
        'pages.profile.cosmetic_dentistry': 'Αισθητική Οδοντιατρική',
        'pages.profile.initial_consultation': 'Αρχική Συνεδρία',
        'pages.profile.video_consultation': 'Βίντεο-Συνεδρία',
        'pages.profile.dental_cleaning': 'Καθαρισμός Δοντιών',
        'pages.profile.fluoride_treatment': 'Φθορίωση',
        'pages.profile.dental_sealants': 'Προληπτικές Εμφράξεις',
        'pages.profile.teeth_whitening': 'Λεύκανση Δοντιών',
        'pages.profile.porcelain_veneers': 'Όψεις Πορσελάνης',
        'pages.profile.invisalign_consultation': 'Συνεδρία Invisalign',
        'pages.profile.free': 'Δωρεάν',
        'pages.profile.review1_text': 'Η Δρ. Wilson είναι καταπληκτική!',
        'pages.profile.review2_text': 'Η καλύτερη εμπειρία που είχα.',
        'pages.profile.review3_text': 'Εξαιρετική εξυπηρέτηση.',
        'pages.profile.weeks_ago': 'εβδομάδες πριν',
        'pages.profile.month_ago': 'μήνα πριν',
        'pages.profile.months_ago': 'μήνες πριν',
        'pages.booking.title': 'Κλείστε Ραντεβού',
        'pages.booking.step1': 'Υπηρεσία',
        'pages.booking.step2': 'Ώρα',
        'pages.booking.step3': 'Στοιχεία',
        'pages.booking.step4': 'Επιβεβαίωση',
        'pages.booking.review_confirm': 'Έλεγχος & Επιβεβαίωση',
        'pages.booking.service': 'Υπηρεσία',
        'pages.booking.date_time': 'Ημερομηνία & Ώρα',
        'pages.booking.patient': 'Ασθενής',
        'pages.booking.total': 'Σύνολο',
        'pages.booking.back': 'Πίσω',
        'pages.booking.continue': 'Συνέχεια',
        'pages.booking.confirm_booking': 'Επιβεβαίωση Κράτησης',
        'pages.booking.confirm_date_time': 'Επιβεβαίωση Ημερομηνίας & Ώρας',
        'pages.booking.date': 'Ημερομηνία',
        'pages.booking.time': 'Ώρα',
        'pages.booking.change_step_hint': 'Μπορείτε να το αλλάξετε στο προηγούμενο βήμα.',
        'pages.booking.patient_details': 'Στοιχεία Ασθενούς',
        'pages.booking.first_name': 'Όνομα',
        'pages.booking.last_name': 'Επώνυμο',
        'pages.booking.email': 'Email',
        'pages.booking.phone': 'Τηλέφωνο',
        'pages.booking.success_title': 'Το ραντεβού επιβεβαιώθηκε!',
        'pages.booking.success_desc': 'Το ραντεβού σας κλείστηκε με επιτυχία.',
        'pages.booking.view_appointments': 'Προβολή των Ραντεβού μου',
        'pages.booking.mock_date': 'Τετ, 14 Οκτ • 10:00 πμ',
        'pages.booking.mock_service': 'Οδοντιατρικός Έλεγχος',
        'pages.booking.required': 'είναι απαραίτητο',
        'pages.booking.invalid_email': 'Μη έγκυρο email',
        'pages.booking.invalid_phone': 'Απαιτείται έγκυρο τηλέφωνο',
        'pages.booking.placeholder_first_name': 'Γιάννης',
        'pages.booking.placeholder_last_name': 'Παπαδόπουλος',
        'pages.booking.placeholder_email': 'giannis@example.com',
        'pages.booking.placeholder_phone': '6912345678',
        'pages.booking.prepayment_patient': '50€ προκαταβολή — αφαιρείται από το τελικό ποσό',
        'pages.booking.prepayment_dentist': 'Ο ασθενής έχει προπληρώσει 50€ — υπόλοιπο στο ραντεβού',
        'pages.booking.prepayment_note': 'η προκαταβολή αφαιρείται από το τελικό ποσό εργασιών στο ιατρείο',
        'pages.return_home': 'Επιστροφή στην Αρχική',
        'days.mon': 'Δευ',
        'days.tue': 'Τρι',
        'days.wed': 'Τετ',
        'days.thu': 'Πεμ',
        'days.fri': 'Παρ',
        'days.sat': 'Σαβ',
        'days.sun': 'Κυρ',
        'months.jan': 'Ιαν',
        'months.feb': 'Φεβ',
        'months.mar': 'Μαρ',
        'months.apr': 'Απρ',
        'months.may': 'Μαΐ',
        'months.jun': 'Ιούν',
        'months.jul': 'Ιούλ',
        'months.aug': 'Αυγ',
        'months.sep': 'Σεπ',
        'months.oct': 'Οκτ',
        'months.nov': 'Νοέ',
        'months.dec': 'Δεκ',
        'months.january': 'Ιανουάριος',
        'months.february': 'Φεβρουάριος',
        'months.march': 'Μάρτιος',
        'months.april': 'Απρίλιος',
        'months.may_full': 'Μάιος',
        'months.june': 'Ιούνιος',
        'months.july': 'Ιούλιος',
        'months.august': 'Αύγουστος',
        'months.september': 'Σεπτέμβριος',
        'months.october': 'Οκτώβριος',
        'months.november': 'Νοέμβριος',
        'months.december': 'Δεκέμβριος',
        'days.monday': 'Δευτέρα',
        'days.tuesday': 'Τρίτη',
        'days.wednesday': 'Τετάρτη',
        'days.thursday': 'Πέμπτη',
        'days.friday': 'Παρασκευή',
        'days.saturday': 'Σάββατο',
        'days.sunday': 'Κυριακή',
        'time.am': 'πμ',
        'time.pm': 'μμ',
        'time.min': 'λεπτά',

        // Dashboard
        'dashboard.overview': 'Επισκόπηση',
        'dashboard.bookings': 'Κρατήσεις',
        'dashboard.profile': 'Προφίλ',
        'dashboard.availability': 'Διαθεσιμότητα',
        'dashboard.services': 'Υπηρεσίες',
        'dashboard.my_articles': 'Τα άρθρα μου',
        'dashboard.settings': 'Ρυθμίσεις',
        'dashboard.logout': 'Αποσύνδεση',

        // Dashboard Client
        'dashboard.setup_required': 'Απαιτείται Ρύθμιση Λογαριασμού',
        'dashboard.setup_desc': 'Παρακαλώ ολοκληρώστε τη ρύθμιση του προφίλ σας για να έχετε πρόσβαση σε όλες τις λειτουργίες του πίνακα ελέγχου.',
        'dashboard.go_settings': 'Μετάβαση στις Ρυθμίσεις',
        'dashboard.stats.total_patients': 'Συνολικοί Ασθενείς',
        'dashboard.stats.unique_patients': 'Μοναδικοί ασθενείς όλων των εποχών',
        'dashboard.stats.upcoming_bookings': 'Επερχόμενες Κρατήσεις',
        'dashboard.stats.recent_future': 'Πρόσφατα και μελλοντικά ραντεβού',
        'dashboard.stats.average_rating': 'Μέση Βαθμολογία',
        'dashboard.stats.verified_reviews': 'επαληθευμένες κριτικές',
        'dashboard.stats.total_revenue': 'Συνολικά Έσοδα',
        'dashboard.stats.from_confirmed': 'Από επιβεβαιωμένα ραντεβού',
        'dashboard.clinic_closed': 'Κλειστό Ιατρείο Σήμερα',
        'dashboard.clinic_open': 'Ανοιχτό Ιατρείο Σήμερα',
        'dashboard.clinic_closed_desc': 'Η σημερινή μέρα έχει επισημανθεί ως μη διαθέσιμη. Κανένας ασθενής δεν μπορεί να κλείσει ραντεβού για σήμερα.',
        'dashboard.clinic_open_desc': 'Είστε ανοιχτά σήμερα από',
        'dashboard.to': 'έως',
        'dashboard.change': 'Αλλαγή',
        'dashboard.profile_review': 'Προφίλ Υπό Εξέταση',
        'dashboard.verification_required': 'Απαιτείται Επαλήθευση',
        'dashboard.docs_reviewed': 'Τα έγγραφά σας εξετάζονται.',
        'dashboard.upload_degree': 'Ανεβάστε το επαγγελματικό σας πτυχίο.',
        'dashboard.submit': 'Υποβολή',
        'dashboard.complete_payment': 'Ολοκλήρωση Ρύθμισης Πληρωμών',
        'dashboard.setup_payment': 'Ρύθμιση Πληρωμών',
        'dashboard.in_progress': 'Σε Εξέλιξη',
        'dashboard.stripe_incomplete': 'Ο λογαριασμός σας Stripe δημιουργήθηκε αλλά χρειάζεται περισσότερες πληροφορίες για να αρχίσετε να λαμβάνετε πληρωμές. Ολοκληρώστε την επαλήθευση τώρα.',
        'dashboard.stripe_required': 'Για να λαμβάνετε πληρωμές από κρατήσεις, πρέπει να συνδέσετε τον λογαριασμό σας Stripe. Αυτό απαιτείται για να εμφανιστεί το προφίλ σας στους ασθενείς.',
        'dashboard.resume_stripe': 'Συνέχιση Ρύθμισης Stripe',
        'dashboard.connect_stripe': 'Σύνδεση Stripe',
        'dashboard.dentist_dashboard': 'Πίνακας Ελέγχου Οδοντιάτρου',
        'dashboard.welcome_dentist': 'Καλώς ήρθατε! Διαχειριστείτε το ιατρείο σας με δεδομένα σε πραγματικό χρόνο.',
        'dashboard.upcoming_appointments': 'Επερχόμενα Ραντεβού',
        'dashboard.view_all': 'Προβολή Όλων',
        'dashboard.no_upcoming': 'Δεν βρέθηκαν επερχόμενα ραντεβού.',
        'dashboard.quick_actions': 'Γρήγορες Ενέργειες',
        'dashboard.update_availability': 'Ενημέρωση Διαθεσιμότητας',
        'dashboard.manage_services': 'Διαχείριση Υπηρεσιών',
        'dashboard.view_reviews': 'Προβολή Όλων των Κριτικών',
        'dashboard.my_dashboard': 'Ο Πίνακας Ελέγχου μου',
        'dashboard.patient_welcome': 'Παρακολουθήστε τη στοματική σας υγεία και τα ραντεβού σας.',
        'dashboard.upcoming': 'Επερχόμενα',
        'dashboard.completed': 'Ολοκληρωμένα',
        'dashboard.are_you_dentist': 'Είστε Οδοντίατρος;',
        'dashboard.dentist_promo': 'Δημιουργήστε το επαγγελματικό σας προφίλ, διαχειριστείτε ραντεβού και αναπτύξτε το ιατρείο σας με το Dentist Anytime.',
        'dashboard.switch_dentist': 'Αλλαγή σε Λογαριασμό Οδοντιάτρου',
        'dashboard.find_new_dentist': 'Βρείτε Νέο Οδοντίατρο',
        'dashboard.prepaid': 'ΠΡΟΠΛΗΡΩΜΕΝΟ',
        'dashboard.no_upcoming_patient': 'Δεν βρέθηκαν επερχόμενα ραντεβού.',
        'dashboard.book_first': 'Κλείστε το Πρώτο σας Ραντεβού',

        // Profile Form
        'profile.title': 'Δημόσιο Προφίλ',
        'profile.subtitle': 'Διαχειριστείτε πώς εμφανίζεται το προφίλ σας στους ασθενείς.',
        'profile.saving': 'Αποθήκευση...',
        'profile.save_changes': 'Αποθήκευση Αλλαγών',
        'profile.photo_title': 'Φωτογραφία Προφίλ',
        'profile.change_photo': 'Αλλαγή Φωτογραφίας',
        'profile.photo_hint': 'JPG, PNG ή GIF. Μέγιστο μέγεθος 2MB.',
        'profile.basic_info': 'Βασικές Πληροφορίες',
        'profile.full_name': 'Ονοματεπώνυμο',
        'profile.specialty': 'Ειδικότητα',
        'profile.experience': 'Έτη Εμπειρίας',
        'profile.price': 'Κόστος Επίσκεψης (€)',
        'profile.clinic_address': 'Διεύθυνση Ιατρείου',
        'profile.search_address': 'Αναζήτηση Διεύθυνσης',
        'profile.search_address_hint': 'Ξεκινήστε να πληκτρολογείτε τη διεύθυνση του ιατρείου σας για να συμπληρωθούν αυτόματα τα παρακάτω πεδία',
        'profile.search_placeholder': 'Αναζήτηση για τη διεύθυνση του ιατρείου σας...',
        'profile.city': 'Πόλη',
        'profile.city_placeholder': 'π.χ. Θεσσαλονίκη',
        'profile.street': 'Οδός',
        'profile.street_placeholder': 'π.χ. Τσιμισκή',
        'profile.house_number': 'Αριθμός Κτιρίου/Οδού',
        'profile.house_number_placeholder': 'π.χ. 42',
        'profile.coordinates_saved': '✓ Οι συντεταγμένες τοποθεσίας αποθηκεύτηκαν — το ιατρείο σας θα εμφανιστεί στον χάρτη',
        'profile.bio_title': 'Επαγγελματικό Βιογραφικό',
        'profile.about_me': 'Σχετικά με εμένα',
        'profile.about_placeholder': 'Πείτε στους ασθενείς για την εμπειρία και την προσέγγισή σας...',
        'profile.education': 'Εκπαίδευση & Πιστοποιήσεις',
        'profile.education_placeholder': 'Αναφέρετε τα πτυχία και την εξειδικευμένη εκπαίδευσή σας...',
        'profile.verification_status': 'Κατάσταση Επαλήθευσης',
        'profile.verified': 'Επαληθευμένο',
        'profile.under_review': 'Υπό Εξέταση',
        'profile.not_verified': 'Μη Επαληθευμένο',
        'profile.verification_hint': 'Για να ενεργοποιήσετε το προφίλ σας και να επιτρέψετε στους ασθενείς να κλείνουν ραντεβού, πρέπει να ανεβάσετε το επαγγελματικό σας πτυχίο ή πιστοποίηση για εξέταση.',
        'profile.upload_degree': 'Φόρτωση Πτυχίου (URL Εικόνας)',
        'profile.degree_placeholder': 'Επικολλήστε το αρχείο URL της εικόνας του πτυχίου σας',
        'profile.submit': 'Υποβολή',
        'profile.degree_reviewing': 'Το πτυχίο σας εξετάζεται αυτήν τη στιγμή από την ομάδα μας. Θα ειδοποιηθείτε μόλις επαληθευτεί.',
        'profile.fully_verified': 'Ο λογαριασμός σας είναι πλήρως επαληθευμένος και ορατός στους ασθενείς.',

        // Bookings
        'bookings.title': 'Ραντεβού',
        'bookings.subtitle': 'Διαχειριστείτε και παρακολουθήστε όλες τις κρατήσεις των ασθενών σας.',
        'bookings.calendar_view': 'Προβολή Ημερολογίου',
        'bookings.export_list': 'Εξαγωγή Λίστας',
        'bookings.recent': 'Πρόσφατες Κρατήσεις',
        'bookings.patient': 'Ασθενής',
        'bookings.service': 'Υπηρεσία',
        'bookings.date_time': 'Ημερομηνία & Ώρα',
        'bookings.status': 'Κατάσταση',
        'bookings.actions': 'Ενέργειες',
        'bookings.no_bookings': 'Δεν βρέθηκαν κρατήσεις.',


        // Availability
        'availability.manage': 'Διαχείριση Διαθεσιμότητας',
        'availability.manage_desc': 'Οργανώστε το εβδομαδιαίο σας πρόγραμμα και διαχειριστείτε εξαιρέσεις για συγκεκριμένες ημερομηνίες.',
        'availability.calendar_view': 'Προβολή Ημερολογίου',
        'availability.weekly_schedule': 'Εβδομαδιαίο Πρόγραμμα',
        'availability.custom_day': 'Οργάνωση Προσαρμοσμένης Ημέρας',
        'availability.custom_day_desc': 'Κάντε κλικ σε οποιαδήποτε ημέρα για να προσαρμόσετε με ακρίβεια τις ώρες εργασίας σας για τη συγκεκριμένη ημερομηνία. Μπορείτε να προσθέσετε πολλαπλά μπλοκ ώρας (π.χ. πρωί και απόγευμα) ή να δηλώσετε κλειστά.',
        'availability.standard_weekly': 'Τυπικό Εβδομαδιαίο Πρόγραμμα',
        'availability.standard_weekly_desc': 'Αυτά τα μπλοκ θα επαναλαμβάνονται κάθε εβδομάδα εκτός εάν αντικατασταθούν στο ημερολόγιο.',
        'availability.save_weekly': 'Αποθήκευση Εβδομαδιαίου Προγράμματος',
        'availability.enabled': 'Ενεργοποιημένο',
        'availability.disabled': 'Απενεργοποιημένο',
        'availability.add_block': 'Προσθήκη Άλλου Μπλοκ',
        'availability.no_hours': 'Δεν έχουν οριστεί ώρες. Το ιατρείο είναι κλειστό αυτήν την ημέρα.',
        'availability.edit_all_hours': 'Επεξεργασία Όλων Των Ωρών',
        'availability.available': 'Διαθέσιμο',
        'availability.closed': 'Κλειστό',
        'availability.click_any_day': 'Κάντε κλικ σε οποιαδήποτε ημέρα για να διαχειριστείτε πολλαπλά μπλοκ ώρας και κενά.',
        'availability.edit_day': 'Επεξεργασία Ημέρας',
        'availability.clinic_status': 'Κατάσταση Ιατρείου',
        'availability.clinic_status_desc': 'Το ιατρείο δέχεται ραντεβού για αυτήν την ημέρα;',
        'availability.available_blocks': 'Διαθέσιμα Μπλοκ Ώρας',
        'availability.starts_at': 'Ξεκινά Στις',
        'availability.ends_at': 'Τελειώνει Στις',
        'availability.add_time_block': 'Προσθήκη Άλλου Μπλοκ Ώρας',
        'availability.clinic_is_closed': 'Το Ιατρείο είναι ΚΛΕΙΣΤΟ',
        'availability.no_slots': 'Δεν θα δημιουργηθούν ώρες. Αυτή η μέρα θα είναι εντελώς αποκλεισμένη για όλους τους ασθενείς.',
        'availability.reset_day': 'Επαναφορά Ημέρας',
        'availability.save_variations': 'Αποθήκευση Αλλαγών',
        'availability.more': 'ακόμη',
        'availability.override': 'Εξαίρεση',

        // Services
        'services.title': 'Υπηρεσίες & Τιμοκατάλογος',
        'services.subtitle': 'Καταχωρίστε τις οδοντιατρικές υπηρεσίες που προσφέρετε και τις τιμές τους.',
        'services.add': 'Προσθήκη Υπηρεσίας',
        'services.name': 'Όνομα Υπηρεσίας',
        'services.name_placeholder': 'π.χ. Λεύκανση Δοντιών',
        'services.price': 'Τιμή (€)',
        'services.duration': 'Διάρκεια (λεπτά)',
        'services.no_services': 'Δεν έχουν προστεθεί υπηρεσίες ακόμη. Κάντε κλικ στην "Προσθήκη Υπηρεσίας" για να ξεκινήσετε.',
        'services.updated': 'Οι υπηρεσίες ενημερώθηκαν!',
        'services.failed': 'Αποτυχία ενημέρωσης υπηρεσιών.',

        // Settings
        'settings.title': 'Ρυθμίσεις',
        'settings.subtitle': 'Διαχειριστείτε τις ρυθμίσεις και τις προτιμήσεις του λογαριασμού σας.',
        'settings.email_notif': 'Ειδοποιήσεις Email',
        'settings.new_bookings': 'Νέες Κρατήσεις',
        'settings.new_bookings_desc': 'Λάβετε email όταν ένας νέος ασθενής κλείνει ραντεβού.',
        'settings.reminders': 'Υπενθυμίσεις',
        'settings.reminders_desc': 'Λάβετε υπενθυμίσεις για επερχόμενα ραντεβού.',
        'settings.danger_zone': 'Ζώνη Κινδύνου',
        'settings.delete_account': 'Διαγραφή Λογαριασμού',
        'settings.delete_account_desc': 'Διαγράψτε οριστικά τον λογαριασμό σας και όλα τα δεδομένα. Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
        'settings.deleting': 'Διαγραφή...',
        'settings.delete_confirm': 'Είστε βέβαιοι ότι θέλετε να διαγράψετε τον λογαριασμό σας; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
        'settings.delete_error': 'Παρουσιάστηκε σφάλμα κατά τη διαγραφή του λογαριασμού σας. Παρακαλώ προσπαθήστε ξανά.',

        // Blog
        'blog.my_articles_title': 'Τα Άρθρα Μου',
        'blog.my_articles_desc': 'Διαχειριστείτε τις κλινικές γνωμοδοτήσεις και συμβουλές των ασθενών σας.',
        'blog.write_new': 'Συγγραφή Νέου Άρθρου',
        'blog.view': 'Προβολή',
        'blog.edit': 'Επεξεργασία',
        'blog.no_articles': 'Δεν υπάρχουν άρθρα',
        'blog.share_expertise': 'Μοιραστείτε την εμπειρία σας με τους ασθενείς σας γράφοντας το πρώτο σας άρθρο.',
        'blog.start_writing': 'Ξεκινήστε',
        'blog.delete_confirm': 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το άρθρο;',
        'blog.delete_failed': 'Αποτυχία διαγραφής',

        // Blog Editor
        'blog.back': 'Πίσω στα Άρθρα Μου',
        'blog.write_title': 'Συγγραφή Νέου Άρθρου',
        'blog.publish': 'Δημοσίευση Άρθρου',
        'blog.publishing': 'Δημοσίευση...',
        'blog.titles': 'Τίτλοι',
        'blog.en_title': 'Αγγλικός Τίτλος',
        'blog.en_title_ph': 'e.g. The importance of daily flossing',
        'blog.el_title': 'Ελληνικός Τίτλος',
        'blog.el_title_ph': 'π.χ. Η σημασία του καθημερινού νήματος',
        'blog.content_title': 'Περιεχόμενο Άρθρου',
        'blog.en_content': 'Αγγλικό Περιεχόμενο',
        'blog.en_content_ph': 'Write your article in English...',
        'blog.el_content': 'Ελληνικό Περιεχόμενο',
        'blog.el_content_ph': 'Γράψτε το άρθρο σας στα Ελληνικά...',
        'blog.settings': 'Ρυθμίσεις',
        'blog.category': 'Κατηγορία',
        'blog.cat_tips': 'Συμβουλές',
        'blog.cat_case': 'Κλινικό Περιστατικό',
        'blog.cat_tech': 'Τεχνολογία',
        'blog.cat_news': 'Νέα Ιατρείου',
        'blog.slug': 'Προσαρμοσμένο Slug (Προαιρετικό)',
        'blog.slug_ph': 'the-importance-of-flossing',
        'blog.slug_hint': 'Αφήστε το κενό για αυτόματη δημιουργία από τον τίτλο.',
        'blog.cover_image': 'Εικόνα Εξωφύλλου',
        'blog.image_url': 'URL Εικόνας',
        'blog.image_ph': 'Επικόλληση URL εικόνας...',
        'blog.create_failed': 'Αποτυχία δημιουργίας άρθρου',
    }
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('el') // Greek as main language

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language
        if (savedLang && (savedLang === 'en' || savedLang === 'el')) {
            setLanguage(savedLang)
        }
    }, [])

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang)
        localStorage.setItem('language', lang)
        document.documentElement.lang = lang
    }

    const t = (key: string): string => {
        return (translations as any)[language][key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
